### ISSUE TITLE
Using blob file handler throws ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by gokhalesujit** [GMOD/tabix-js#142]
I am getting error - ReferenceError: Blob is not defined during "runtime" (not compile time) when running following code. I have also pasted tsconfig.json. The intent is to get tabix files from AWS s3 bucket.

**Code**
```js
const zipFile = await getS3FileBlob('bucket', `file.txt.gz`);
const tbiFile = await getS3FileBlob('bucket', `file.txt.gz.tbi`);
    
const zipBlob = new BlobFile(new Blob([zipFile]));
const tbiFileBlob = new BlobFile(new Blob([tbiFile]));

const tbiIndexed = new TabixIndexedFile({
   filehandle: zipBlob,
   tbiFilehandle: tbiFileBlob,
});
```

**tsconfig.json -** 
```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "lib": [
      "DOM",
      "ES2018"
    ],
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "outDir": "build",
    "baseUrl": "./src",
    "paths": {
      "@common/*": [
        "common/*"
      ]
    }
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "build",
  ]
}
```

**Comment by gokhalesujit** [comment]
Using "WebWorker" instead of DOM in the tsconfig.json "lib" gives same error.

**Comment by garrettjstevens** [comment]
Are you running this in Node.js or in the browser? If you're using Node.js, make sure you're at least on v18. Is `getS3FileBlob` your own function or imported from a library? I can't seem to find anything on Google about accessing S3 objects as `Blob`s.

Generally the main use case for `Blob`s is reading a local file in the browser, since a `File` is a `Blob`.

Since you're working with S3, you may want to use `RemoteFile` instead of `BlobFile` with the URL of the S3 object.

**Comment by gokhalesujit** [comment]
Thank you for getting back. I am running this on server side node.js in AWS Lambda. Here is the helper function to get file binary data from S3. Not sure if "RemoteFile" works against s3 url (s3:/..).  Let me try upgrading to node v18.

```js
import * as AWS from '@aws-sdk/client-s3';
const client = new AWS.S3({});

const getS3FileBlob = async (bucket: string, key: string) : Promise<Uint8Array> => {
  const command = new AWS.GetObjectCommand({
    Bucket: bucket,
    Key: key
  });

  const response = await client.send(command);
  if (response.Body) {
    return await response.Body.transformToByteArray();
  } else {
    throw new Error(`No data found for s3 file - s3:/${bucket}/${key}`); 
  }
};

export default client;
export { getS3FileBlob };
```

**Comment by gokhalesujit** [comment]
Upgraded to Node version 18.12.0 (that is supported by AWS Lambda). I am now getting following error in "runtime". May be this needs a fix in generic-filehandle module to use "fs" (for server side node js) if FileReader" is undefined?

```
ReferenceError: FileReader is not defined
    at readBlobAsArrayBuffer (/Users/xxx/node_modules/generic-filehandle/dist/blobFile.js:16:24)
    at BlobFile.<anonymous> (/Users/xxx/node_modules/generic-filehandle/dist/blobFile.js:98:34)
    at Generator.next (<anonymous>)
    at /Users/xxx/node_modules/generic-filehandle/dist/blobFile.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/node_modules/generic-filehandle/dist/blobFile.js:4:12)
    at BlobFile.readFile (/Users/xxx/node_modules/generic-filehandle/dist/blobFile.js:84:16)
    at TabixIndex.<anonymous> (/Users/xxx/node_modules/@gmod/tabix/dist/tbi.js:83:47)
    at Generator.next (<anonymous>)
    at /Users/xxx/node_modules/@gmod/tabix/dist/tbi.js:31:71
```

**Comment by garrettjstevens** [comment]
I think you might have better luck trying something other then `Blob`, since that's mainly for use in the browser.

For the URL, I was meaning the http URL of the S3 object, such as `https://s3.amazonaws.com/jsb-public/classic_amazon_door_desk.png` (or equivalently `https://jsb-public.s3.amazonaws.com/classic_amazon_door_desk.png`, see [here](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/). This will only work if the object in S3 is public or otherwise set up to be accessible from your Lambda function. You could also generate a presigned URL that is public and accessible from your Lambda, see [here](https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/).

You could also write to the file to the `/tmp` directory on the Lambda instance and then use `path` and `tbiPath` without having to use `generic-filehandle` at all.

**Comment by garrettjstevens** [comment]
Also, if you do really have to use a `Blob`, you might try polyfilling `FileReader` with https://www.npmjs.com/package/filereader.

**Comment by cmdcolin** [comment]
@gokhalesujit did you run into any more issues? maybe can close for now
